In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('../resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
X = df.copy()
X = df.drop(columns=['loan_status'])
X = pd.get_dummies(df)


# Create our target
y = df['loan_status']

In [7]:
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [8]:
y.head()

0    low_risk
1    low_risk
2    low_risk
3    low_risk
4    low_risk
Name: loan_status, dtype: object

In [9]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.994958,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.070831,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,1.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,1.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [10]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify= y)

print(Counter(y_train))
print(Counter(y_test))

Counter({'low_risk': 51352, 'high_risk': 260})
Counter({'low_risk': 17118, 'high_risk': 87})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [12]:
# Resample the training data with the BalancedRandomForestClassifier
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Create a random forest classifier.
from imblearn.ensemble import BalancedRandomForestClassifier
brfc_model = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fitting the model
brfc_model = brfc_model.fit(X_train_scaled, y_train)
brfc_model

BalancedRandomForestClassifier(random_state=1)

In [13]:
# Calculated the balanced accuracy score
predictions = brfc_model.predict(X_test_scaled)
balanced_accuracy_score(y_test, predictions)

0.9994742376445847

In [14]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   87                   0
Actual Low Risk                    18               17100

In [15]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.83      1.00      1.00      0.91      1.00      1.00        87
   low_risk       1.00      1.00      1.00      1.00      1.00      1.00     17118

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205

In [16]:
# List the features sorted in descending order by feature importance
sorted(zip(brfc_model.feature_importances_, X.columns), reverse=True)

[(0.3715871193693003, 'loan_status_high_risk'),
 (0.23907429991706192, 'loan_status_low_risk'),
 (0.04579021813384743, 'total_rec_int'),
 (0.036208792956783385, 'last_pymnt_amnt'),
 (0.0320114185782304, 'total_rec_prncp'),
 (0.029545706488902583, 'total_pymnt'),
 (0.02597544849644188, 'total_pymnt_inv'),
 (0.010137282750394556, 'int_rate'),
 (0.007597863806321944, 'dti'),
 (0.0070253860367966965, 'out_prncp'),
 (0.005577055841818609, 'revol_bal'),
 (0.005478984599840578, 'issue_d_Mar-2019'),
 (0.005354317026676112, 'max_bal_bc'),
 (0.005296459239582083, 'installment'),
 (0.005238893249146484, 'total_bal_ex_mort'),
 (0.005202686977433921, 'mo_sin_old_rev_tl_op'),
 (0.0050830950875427475, 'il_util'),
 (0.005048817394171602, 'mths_since_recent_inq'),
 (0.004765601726530036, 'loan_amnt'),
 (0.004757737615883966, 'out_prncp_inv'),
 (0.004752724736914683, 'mths_since_rcnt_il'),
 (0.0047440432922275675, 'all_util'),
 (0.004713439123636187, 'bc_util'),
 (0.004667636998875079, 'annual_inc'),
 (0.004500218052210715, 'avg_cur_bal'),
 (0.004342395037385082, 'total_bal_il'),
 (0.004284561017388593, 'total_bc_limit'),
 (0.004122669096809495, 'tot_hi_cred_lim'),
 (0.0039545823642321495, 'bc_open_to_buy'),
 (0.0038637901031692724, 'total_rev_hi_lim'),
 (0.003802480478725338, 'num_rev_accts'),
 (0.0037476052204779738, 'issue_d_Jan-2019'),
 (0.0037433870186311985, 'num_bc_tl'),
 (0.0036047951373615757, 'mo_sin_old_il_acct'),
 (0.0035577071928639113, 'total_rec_late_fee'),
 (0.0034882107681212643, 'total_il_high_credit_limit'),
 (0.0032002054780475003, 'mths_since_recent_bc'),
 (0.003063317818635879, 'total_acc'),
 (0.003013843563556811, 'tot_cur_bal'),
 (0.002951958249030132, 'num_tl_op_past_12m'),
 (0.002936323409360474, 'inq_last_12m'),
 (0.002922388233509131, 'pct_tl_nvr_dlq'),
 (0.002852328944730043, 'num_rev_tl_bal_gt_0'),
 (0.002847970217193001, 'open_acc'),
 (0.0028229930784375913, 'num_sats'),
 (0.0027655814148425124, 'acc_open_past_24mths'),
 (0.0026546460731560993, 'num_op_rev_tl'),
 (0.00247556917820709, 'mort_acc'),
 (0.0024613830113617975, 'mo_sin_rcnt_rev_tl_op'),
 (0.0023652908447103576, 'delinq_2yrs'),
 (0.0023638227402272873, 'num_actv_rev_tl'),
 (0.002343576413522751, 'total_cu_tl'),
 (0.002293190673415925, 'num_il_tl'),
 (0.002253115122961667, 'num_bc_sats'),
 (0.0020941194775513884, 'open_il_24m'),
 (0.0020743203837022377, 'next_pymnt_d_Apr-2019'),
 (0.0019747352486298815, 'mo_sin_rcnt_tl'),
 (0.0018212571527107951, 'inq_fi'),
 (0.0017126834199608415, 'open_acc_6m'),
 (0.0017055854243826398, 'inq_last_6mths'),
 (0.001682196915641885, 'open_rv_24m'),
 (0.0016771452637591893, 'percent_bc_gt_75'),
 (0.0015798693282100937, 'num_actv_bc_tl'),
 (0.001366198504333101, 'open_act_il'),
 (0.001321127824700818, 'next_pymnt_d_May-2019'),
 (0.00130260722027455, 'open_il_12m'),
 (0.001228004677553213, 'tot_coll_amt'),
 (0.0010250001251962061, 'issue_d_Feb-2019'),
 (0.0009087728743750109, 'open_rv_12m'),
 (0.0006377348194244531, 'initial_list_status_f'),
 (0.0005907691128727041, 'application_type_Individual'),
 (0.0005618993679325022, 'home_ownership_OWN'),
 (0.0004821190623857871, 'verification_status_Verified'),
 (0.0004652286193248137, 'verification_status_Not Verified'),
 (0.00045163233625599423, 'pub_rec'),
 (0.0003553064439581152, 'pub_rec_bankruptcies'),
 (0.0003436005241006467, 'home_ownership_MORTGAGE'),
 (0.0003360714895940997, 'initial_list_status_w'),
 (0.0003026507485363374, 'num_tl_90g_dpd_24m'),
 (0.0002568181741688081, 'application_type_Joint App'),
 (0.00019059112776867866, 'home_ownership_RENT'),
 (0.00017381144909452587, 'verification_status_Source Verified'),
 (0.00014320748695748696, 'num_accts_ever_120_pd'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'home_ownership_ANY'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collections_12_mths_ex_med'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'chargeoff_within_12_mths'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [17]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

eec_model = EasyEnsembleClassifier(n_estimators=100, random_state=1)

eec_model = eec_model.fit(X_train_scaled, y_train)

In [18]:
# Calculated the balanced accuracy score
predictions = eec_model.predict(X_test_scaled)
balanced_accuracy_score(y_test, predictions)

1.0

In [20]:
# Display the confusion matrix
y_pred = eec_model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[    0,    87],
       [    0, 17118]], dtype=int64)

In [21]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       1.00      1.00      1.00      1.00      1.00      1.00        87
   low_risk       1.00      1.00      1.00      1.00      1.00      1.00     17118

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     17205